/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hawkshop_top01.view;
import hawkshop_top01.entity.voucher;
import hawkshop_top01.images.TableAcitionEvent;
import hawkshop_top01.service.Voucher_service;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
/**
 *
 * @author khuat
 */
public class Action_voucher extends javax.swing.JPanel {

    /**
     * Creates new form Action_voucher
     */
    public Action_voucher() {
        initComponents();
        
    }
    public void initEvent(TableAcitionEvent event , int row){
        cmdbut.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               
            }
        });
        cmdx.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
               
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionButton1 = new hawkshop_top01.images.ActionButton();
        actionButton2 = new hawkshop_top01.images.ActionButton();
        actionButton3 = new hawkshop_top01.images.ActionButton();
        actionButton4 = new hawkshop_top01.images.ActionButton();
        actionButton5 = new hawkshop_top01.images.ActionButton();
        actionButton6 = new hawkshop_top01.images.ActionButton();
        cmdbut = new hawkshop_top01.images.ActionButton();
        cmdx = new hawkshop_top01.images.ActionButton();

        cmdbut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hawkshop_top01/images/icons/sua.png"))); // NOI18N
        cmdbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdbutActionPerformed(evt);
            }
        });

        cmdx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hawkshop_top01/images/icons/Delete.png"))); // NOI18N
        cmdx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(cmdbut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmdx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdx, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdbut, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdxActionPerformed
   
    }//GEN-LAST:event_cmdxActionPerformed

    private void cmdbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdbutActionPerformed
        Frame fe  = null;
        Sua_voucher1 sv = new Sua_voucher1(fe, true);
        sv.setVisible(true);  
        
    }//GEN-LAST:event_cmdbutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private hawkshop_top01.images.ActionButton actionButton1;
    private hawkshop_top01.images.ActionButton actionButton2;
    private hawkshop_top01.images.ActionButton actionButton3;
    private hawkshop_top01.images.ActionButton actionButton4;
    private hawkshop_top01.images.ActionButton actionButton5;
    private hawkshop_top01.images.ActionButton actionButton6;
    private hawkshop_top01.images.ActionButton cmdbut;
    private hawkshop_top01.images.ActionButton cmdx;
    // End of variables declaration//GEN-END:variables

   
}
